[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "tv-tantrum"

[services.variables]
NODE_ENV = "production"
PORT = "${{ PORT }}"

[services.healthcheck]
path = "/api/health"
interval = 30
timeout = 10
retries = 3