[build]
builder = "nixpacks"

[deploy]
startCommand = "npx tsx server/index.ts"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "3000"
